
const menu = [
    {
      id: 1,
      title: 'YoAudio',
      category: 'reward based',
      like: 161,
      img: './images/gif.gif',
      desc: `YoAudio, our mission is simple: Keep people connected, no matter where they are. We are a community of skiers, snowboarders, mountain bikers – action enthusiasts and families -  who wanted to find a way to always stay safe and connected,  instead of shouting across hilltops and roads. When you’re off the beaten track, phone signal always lets you down, so how can you make sure that you, your friends and family have even more fun …share the vibe and stay safe. Enter YoAudio, we have modernized sport communication  using Bluetooth 5.1 - made  hands free, with a one-touch mute, boosted range and exceptional battery-life. With only 3-buttons The outcome is the perfect companion for  adventures!`,
      progress:78,
      hoursLeft:295,
    },
    {
      id: 2,
      title: '201 Musical Synthesizer',
      category: 'equity based',
      like: 81,
      img: './images/campaign1.png',
      desc: `The 201 is nearly pocket size, but don't let its small size fool you! Under the hood is some powerful circuitry that will allow you to explore your musical ideas quickly and easily. The 201 is built to last. It features a sturdy anodized aluminum enclosure and maple wood buttons for a nice, tactile feel. It will be assembled and tested by hand at our shop in Brooklyn, NY. `,
      progress:26,
      hoursLeft:489,
    },
    {
      id: 3,
      title: 'GaliGear',
      category: 'profit based',
      like: 51,
      img: './images/campaign2.jpg',
      desc: `An interactive learning tool that will encourage kids to explore their creativity and the wonderful world of science and engineering. Encouraging kids to Explore their Creativity and the Incredible World of Science and Engineering. At its core, GaliGear will be an electro-mechanical model of the earth, sun, and moon. More importantly, we envision GaliGear as being an interactive learning tool that will encourage kids to explore their creativity and the incredible world of science and engineering. Kids will learn how to use their hands to build and create, interpret drawings and assembly instructions, how the various disciplines of engineering work together to make something move and react, and how components such as gears and sensors work, all while having fun doing it!  We want GaliGear to engage kids, give them a sense of accomplishment, and show them that learning is fun and exciting. `,
      progress:50,
      hoursLeft:436,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'reward based',
      like: 20,
      img: './images/item-4.jpeg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
      progress:14,
      hoursLeft:87,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'equity based',
      like: 22,
      img: './images/item-5.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
      progress:66,
      hoursLeft:68,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'profit based',
      like: 18,
      img: './images/item-6.jpeg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      progress:77,
      hoursLeft:28,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'reward based',
      like: 8,
      img: './images/item-7.jpeg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
      progress:100,
      hoursLeft:4,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'equity based',
      like: 12,
      img: './images/item-8.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
      progress:10,
      hoursLeft:285,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'profit based',
      like: 16,
      img: './images/item-9.jpeg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      progress:50,
      hoursLeft:167,
    },
    {
      id: 10,
      title: 'diner double',
      category: 'donation based',
      like: 13,
      img: './images/item-2.jpeg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats asdfsadfsadfasdfasdfasdfasdfxasdfasdfasdfxasdf asdfasdfasdfa sdfasdfasdfasdf asdfasdfa sdfasdfasdfa sdfasdfsadf asdfasdfa sdfasdf asdfasdf asdf asdf asdfasd fasdfas df asdfasdf asdf asdf asdf asdf asd fzasdx fasdxz `,
      progress:27,
      hoursLeft:218,
    },
  ];
  export default menu;
  