
const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'reward based',
    like: 16,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed asdfasdf asdfasdf sadf asd fsadf xasd xfsad fsd afs adfsa df asdsa dfsda fas df asdf sadf asdf asdf sad fsda fsad fasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdf asdf asdfasd fsdafd asd fasdf asdfasdfasdf asdfasd fasd fasdf asd fasd fxasdf asdf asdfzI'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed asdfasdf asdfasdf sadf asd fsadf xasd xfsad fsd afs adfsa df asdsa dfsda fas df asdf sadf asdf asdf sad fsda fsad fasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdf asdf asdfasd fsdafd asd fasdf asdfasdfasdf asdfasd fasd fasdf asd fasd fxasdf asdf asdfzI'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed asdfasdf asdfasdf sadf asd fsadf xasd xfsad fsd afs adfsa df asdsa dfsda fas df asdf sadf asdf asdf sad fsda fsad fasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdf asdf asdfasd fsdafd asd fasdf asdfasdfasdf asdfasd fasd fasdf asd fasd fxasdf asdf asdfzI'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed asdfasdf asdfasdf sadf asd fsadf xasd xfsad fsd afs adfsa df asdsa dfsda fas df asdf sadf asdf asdf sad fsda fsad fasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdf asdf asdfasd fsdafd asd fasdf asdfasdfasdf asdfasd fasd fasdf asd fasd fxasdf asdf asdfzI'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed asdfasdf asdfasdf sadf asd fsadf xasd xfsad fsd afs adfsa df asdsa dfsda fas df asdf sadf asdf asdf sad fsda fsad fasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdf asdf asdfasd fsdafd asd fasdf asdfasdfasdf asdfasd fasd fasdf asd fasd fxasdf asdf asdfzI'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed asdfasdf asdfasdf sadf asd fsadf xasd xfsad fsd afs adfsa df asdsa dfsda fas df asdf sadf asdf asdf sad fsda fsad fasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdffasdf asdf asdfasd fsdafd asd fasdf asdfasdfasdf asdfasd fasd fasdf asd fasd fxasdf asdf asdfz `,
    progress:20,
    hoursLeft:113,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'equity based',
    like: 13,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    progress:80,
    hoursLeft:63,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'profit based',
    like: 6,
    img: './images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    progress:50,
    hoursLeft:83,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'reward based',
    like: 20,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    progress:14,
    hoursLeft:87,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'equity based',
    like: 22,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    progress:66,
    hoursLeft:68,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'profit based',
    like: 18,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    progress:77,
    hoursLeft:28,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'reward based',
    like: 8,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    progress:100,
    hoursLeft:4,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'equity based',
    like: 12,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    progress:10,
    hoursLeft:285,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'profit based',
    like: 16,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    progress:50,
    hoursLeft:167,
  },
  {
    id: 10,
    title: 'diner double',
    category: 'donation based',
    like: 13,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats asdfsadfsadfasdfasdfasdfasdfxasdfasdfasdfxasdf asdfasdfasdfa sdfasdfasdfasdf asdfasdfa sdfasdfasdfa sdfasdfsadf asdfasdfa sdfasdf asdfasdf asdf asdf asdfasd fasdfas df asdfasdf asdf asdf asdf asdf asd fzasdx fasdxz `,
    progress:27,
    hoursLeft:218,
  },
];
export default menu;
