
const menu = [
  {
    id: 1,
    title: 'GaliGear',
    category: 'profit based',
    like: 51,
    img: './images/campaign2.jpg',
    desc: `An interactive learning tool that will encourage kids to explore their creativity and the wonderful world of science and engineering. Encouraging kids to Explore their Creativity and the Incredible World of Science and Engineering. At its core, GaliGear will be an electro-mechanical model of the earth, sun, and moon. More importantly, we envision GaliGear as being an interactive learning tool that will encourage kids to explore their creativity and the incredible world of science and engineering. Kids will learn how to use their hands to build and create, interpret drawings and assembly instructions, how the various disciplines of engineering work together to make something move and react, and how components such as gears and sensors work, all while having fun doing it!  We want GaliGear to engage kids, give them a sense of accomplishment, and show them that learning is fun and exciting. `,
    progress:50,
    hoursLeft:436,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'equity based',
    like: 13,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    progress:80,
    hoursLeft:63,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'profit based',
    like: 6,
    img: './images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    progress:50,
    hoursLeft:83,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'reward based',
    like: 20,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    progress:14,
    hoursLeft:87,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'equity based',
    like: 22,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    progress:66,
    hoursLeft:68,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'profit based',
    like: 18,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    progress:77,
    hoursLeft:28,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'reward based',
    like: 8,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    progress:100,
    hoursLeft:4,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'equity based',
    like: 12,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    progress:10,
    hoursLeft:285,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'profit based',
    like: 16,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    progress:50,
    hoursLeft:167,
  },
  {
    id: 10,
    title: 'diner double',
    category: 'donation based',
    like: 13,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats asdfsadfsadfasdfasdfasdfasdfxasdfasdfasdfxasdf asdfasdfasdfa sdfasdfasdfasdf asdfasdfa sdfasdfasdfa sdfasdfsadf asdfasdfa sdfasdf asdfasdf asdf asdf asdfasd fasdfas df asdfasdf asdf asdf asdf asdf asd fzasdx fasdxz `,
    progress:27,
    hoursLeft:218,
  },
];
export default menu;
